[package]
name = "spacetimedb-sql-parser"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file = "LICENSE"
description = "The SpacetimeDB SQL AST and Parser"

[dependencies]
derive_more.workspace = true
#TODO: Remove this once the sqlparser crate is integrated
#sqlparser.workspace = true
sqlparser = "0.57.0"
thiserror.workspace = true
spacetimedb-lib.workspace = true
