[package]
name = "spacetimedb-table"
version = "0.8.1"
edition = "2021"
license-file = "LICENSE"
description = "A database Table implementation and friends"

[[bench]]
name = "pointer_map"
harness = false

[[bench]]
name = "page"
harness = false

[[bench]]
name = "var_len_visitor"
harness = false

[[bench]]
name = "page_manager"
harness = false

[features]
# Allows using `Arbitrary` impls defined in this crate.
proptest = ["dep:proptest", "dep:proptest-derive"]

# Needed for miri
blake3_pure = ["blake3/pure"]

[dependencies]
spacetimedb-primitives = { path = "../primitives" }
spacetimedb-sats = { path = "../sats" }

ahash.workspace = true
bit-vec.workspace = true
blake3.workspace = true
derive_more.workspace = true
enum-as-inner.workspace = true
itertools.workspace = true
nohash-hasher.workspace = true
smallvec.workspace = true
thiserror.workspace = true

# For the 'proptest' feature.
proptest = { workspace = true, optional = true }
proptest-derive = { workspace = true, optional = true }

[dev-dependencies]
criterion.workspace = true
criterion-perf-events.workspace = true
proptest.workspace = true
proptest-derive.workspace = true
rand.workspace = true

[target.'cfg(all(target_os = "linux", target_arch = "x86"))'.dev-dependencies]
perfcnt = "0.8"
