version: "3.6"

services:
  node:
    build:
      context: ./
      dockerfile: ./crates/standalone/Dockerfile
    volumes:
      - ./crates/standalone:/usr/src/app/crates/standalone
      - ./crates/core:/usr/src/app/crates/core
      - ./crates/client-api:/usr/src/app/crates/client-api
      - ./crates/lib:/usr/src/app/crates/lib
      - ./crates/sats:/usr/src/app/crates/sats
      - ./crates/bindings:/usr/src/app/crates/bindings
      - ./crates/bindings-macro:/usr/src/app/crates/bindings-macro
      - ./crates/bindings-sys:/usr/src/app/crates/bindings-sys
      - ./crates/modules/rust-wasm-test:/usr/src/app/crates/modules/rust-wasm-test
      - ./crates/vm:/usr/src/app/crates/vm
      - /stdb
    ports:
      - "3000:80"
    privileged: true
    command: start
    environment:
      RUST_BACKTRACE: 1
      ENV: release
    # Turn on core dumps, hopefully.
    ulimits:
      core:
        soft: -1
        hard: -1

  prometheus:
    build:
      context: ./packages/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./packages/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    build:
      context: ./packages/grafana
    ports:
      - "3001:3000"

