[package]
name = "sdk-test-case-conversion"
version = "0.1.0"
edition.workspace = true
license-file = "LICENSE"

[lib]
crate-type = ["cdylib"]

[dependencies]
log.workspace = true

[dependencies.spacetimedb]
workspace = true
features = ["unstable"]
