[package]
name = "spacetimedb-snapshot"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file = "LICENSE"
description = "Low-level interfaces for capturing and restoring snapshots of database states"

[dependencies]
spacetimedb-table.workspace = true
spacetimedb-lib.workspace = true
spacetimedb-sats = { workspace = true, features = ["blake3"] }
spacetimedb-primitives.workspace = true
spacetimedb-paths.workspace = true
spacetimedb-fs-utils.workspace = true

blake3.workspace = true
bytes.workspace = true
futures.workspace = true
hex.workspace = true
log.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["io-util"] }
tokio-stream.workspace = true
tokio-util = { workspace = true, features = ["io"] }
zstd-framed.workspace = true

[dev-dependencies]
spacetimedb-core = { workspace = true, features = ["test"] }
spacetimedb-schema.workspace = true
spacetimedb-durability.workspace = true

anyhow.workspace = true
env_logger.workspace = true
pretty_assertions = { workspace = true, features = ["unstable"] }
