[package]
name = "spacetimedb-rust-transfer-sim"
version = "0.1.0"
edition = "2024"
description = "Client simulating of transfers and benchmarking TPS for SpacetimeDB"

[dependencies]
spacetimedb-lib.workspace = true
spacetimedb-client-api-messages.workspace = true
http.workspace = true
thiserror.workspace = true
rand.workspace = true
rand_distr.workspace = true
tokio.workspace = true
tokio-tungstenite.workspace = true
log.workspace = true
bytes.workspace = true
futures.workspace = true
itertools.workspace = true
humantime.workspace = true
clap.workspace = true
