[package]
name = "upgrade-version"
version = "0.1.0"
edition.workspace = true
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml_edit = "0.22.4"
anyhow.workspace = true
clap.workspace = true
regex.workspace = true
duct.workspace = true
