[package]
name = "spacetimedb-primitives"
version.workspace = true
edition.workspace = true
license-file = "LICENSE"
description = "Primitives such as TableId and ColumnIndexAttribute"

[dependencies]
spacetimedb-data-structures.workspace = true

either.workspace = true
bitflags.workspace = true

[dev-dependencies]
proptest.workspace = true
