name: Git tree checks

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
  merge_group:
permissions: read-all

jobs:
  check_base_ref:
    name: Release branch restriction
    runs-on: ubuntu-latest
    steps:
      - if: |
          github.event_name == 'pull_request' &&
          github.event.pull_request.base.ref == 'release' &&
          ! startsWith(github.event.pull_request.head.ref, 'release-')
        run: |
          echo 'Only `release-*` branches are allowed to merge into the release branch `release`.'
          echo 'Are you **sure** that you want to merge into release?'
          echo 'Is this **definitely** just cherrypicking commits that are already in `master`?'
          exit 1
