[package]
name = "benchmarks-module"
version = "0.1.0"
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
spacetimedb = { path = "../../crates/bindings" }

anyhow.workspace = true
fake.workspace = true