[package]
name = "sqltest"
version = "0.8.1"
edition = "2021"
description = "Sql integration test for SpacetimeDB"

[dependencies]
spacetimedb-lib = { path = "../lib" }
spacetimedb-core = { path = "../core" }
spacetimedb-sats = { path = "../sats" }

anyhow.workspace = true
async-trait.workspace = true
chrono.workspace = true
clap.workspace = true
console.workspace = true
derive_more.workspace = true
fs-err.workspace = true
futures.workspace = true
glob.workspace = true
itertools.workspace = true
postgres-types.workspace = true
quick-junit.workspace = true
rusqlite.workspace = true
rust_decimal.workspace = true
sqllogictest-engines.workspace = true
sqllogictest.workspace = true
tempfile.workspace = true
tokio.workspace = true
tokio-postgres.workspace = true
