[package]
name = "sqltest"
version.workspace = true
edition.workspace = true
description = "Sql integration test for SpacetimeDB"
license-file = "LICENSE"

[dependencies]
spacetimedb-lib.workspace = true
spacetimedb-core.workspace = true
spacetimedb-sats.workspace = true
spacetimedb-vm.workspace = true

anyhow.workspace = true
async-trait.workspace = true
chrono.workspace = true
clap.workspace = true
console.workspace = true
derive_more.workspace = true
fs-err.workspace = true
futures.workspace = true
glob.workspace = true
itertools.workspace = true
postgres-types.workspace = true
quick-junit.workspace = true
rusqlite.workspace = true
rust_decimal.workspace = true
sqllogictest-engines.workspace = true
sqllogictest.workspace = true
tempfile.workspace = true
tokio.workspace = true
tokio-postgres.workspace = true
