[package]
name = "module-test"
version = "0.0.0"
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html\

[lib]
crate-type = ["cdylib"]
# Benching off, because of https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
bench = false

[dependencies]
spacetimedb = { path = "../../crates/bindings" }

anyhow.workspace = true
log.workspace = true
