[package]
name = "spacetimedb-subscription"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file = "LICENSE"
description = "The SpacetimeDB subscription compiler"

[dependencies]
anyhow.workspace = true
spacetimedb-data-structures.workspace = true
spacetimedb-execution.workspace = true
spacetimedb-expr.workspace = true
spacetimedb-lib.workspace = true
spacetimedb-primitives.workspace = true
spacetimedb-physical-plan.workspace = true
spacetimedb-query.workspace = true
spacetimedb-schema.workspace = true

[lints]
workspace = true
