[package]
name = "spacetime-module"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# Put this in an empty workspace. This is required because we're nested under the SpacetimeDB root
# dir, which has its own workspace `Cargo.toml`, and this shouldn't think it's a part of that.
[workspace]

[lib]
crate-type = ["cdylib"]

[dependencies]
# spacetimedb = { version = "1.0.0-rc2" }
# spacetimedb = { path = "../../../SpacetimeDB/crates/bindings" }
spacetimedb = { git = "https://github.com/ClockworkLabs/SpacetimeDB" }
log = "0.4"
rand = "0.8.5"
