[package]
name = "spacetimedb-vm"
version = "0.8.1"
edition = "2021"
license-file = "LICENSE"
description = "A VM for SpacetimeDB"

[dependencies]
spacetimedb-sats= { path = "../sats", version = "0.8.1" }
spacetimedb-lib = { path = "../lib", version = "0.8.1" }
spacetimedb-primitives = { path = "../primitives", version = "0.8.1" }

anyhow.workspace = true
derive_more.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true
