[package]
name = "spacetimedb-vm"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE"
description = "A VM for SpacetimeDB"
publish = false

[dependencies]
spacetimedb-sats= { path = "../sats" }
spacetimedb-lib = { path = "../lib" }
thiserror = "1.0.37"
anyhow = { version = "1.0.57", features = ["backtrace"] }

[dev-dependencies]
tempdir = "0.3.7"
