[package]
name = "spacetime-replay"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "spacetime-replay"
path = "src/main.rs"
# Benching off, because of https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
bench = false

[dependencies]
imara-diff.workspace = true
tempdir = "0.3.7"
serde_json = "1.0.87"

[dependencies.spacetimedb-core]
path = "../core"

