[package]
name = "spacetimedb-testing"
version.workspace = true
edition.workspace = true

[dependencies]
spacetimedb-cli.workspace = true
spacetimedb-data-structures.workspace = true
spacetimedb-lib.workspace = true
spacetimedb-core.workspace = true
spacetimedb-standalone.workspace = true
spacetimedb-client-api.workspace = true

anyhow.workspace = true
env_logger.workspace = true
log.workspace = true
clap.workspace = true
serde_json.workspace = true
tokio.workspace = true
wasmbin.workspace = true
duct.workspace = true
lazy_static.workspace = true
rand.workspace = true
reqwest.workspace = true
tempfile.workspace = true
serde.workspace = true

[dev-dependencies]
serial_test.workspace = true
