[package]
name = "xtask-llm-benchmark"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
default-run = "llm_benchmark"

[lints]
workspace = true

[dependencies]
spacetimedb.workspace = true
spacetimedb-guard.workspace = true

anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
blake3.workspace = true
clap.workspace = true
chrono = { version = "0.4", features = ["clock", "serde"] }
async-trait = "0.1.89"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
urlencoding = "2.1.3"
reqwest = { version = "0.12", features = ["json"] }
futures = "0.3.31"
regex = "1"
tempfile = "3.23.0"
fs2 = "0.4.3"
heck = "0.5.0"
thiserror = "2.0.17"

[lib]
path = "src/lib.rs"

[[bin]]
name = "llm_benchmark"
path = "src/bin/llm_benchmark.rs"