# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x
    - name: Build client example
      run: dotnet build -warnaserror
      working-directory: examples/quickstart/client
    - name: Verify formatting
      run: dotnet format --check client.sln
      working-directory: examples/quickstart/client
